### ISSUE TITLE
Data bag wildcard syntax errors out

### ISSUE THREAD

**Issue by miketheman** [mattray/spiceweasel#40]
Env:
ruby 1.9.3-p392
chef 11.4.0
spiceweasel 2.1.2

from yml file:

``` yaml
data bags:
  - users:
      items:
      - "*"
```

From execution:

``` console
$ knife data bag from file users *.json miketheman.json
ERROR: Could not find or open file '*.json' in current directory or in 'data_bags/users/*.json'
```

Unless the syntax of invoking this has changed?
