### ISSUE TITLE
Please mention "name:" in the README and/or the examples

### ISSUE THREAD

**Issue by srenatus** [mattray/spiceweasel#42]
Hi,

without knowing about the `name:` option introduced with #32 it's way to easy to delete infrastructure that is _not described in the manifest_.

For example, the manifest

```
berkshelf:
environments:
- testing:
roles:
- appnode:
clusters:
  - testing:
    - openstack 2:
      run_list: role[appnode]
      options: -f 2 -I IMAGEID -S KEYNAME -x root -N app{{n}}
```

used with `spiceweasel -r ex.yml` goes `bulk_delete` and does this:

```
knife node list | xargs knife openstack server delete -y
```

which helps me getting rid of _way more_ than "the infrastructure described in the manifest".

With the manifest like this (snippet),

```
    - openstack 2:
      name: app{{n}}
      run_list: role[appnode]
      options: -f 2 -I IMAGEID -S KEYNAME -x root -N app{{n}}
```

everything is fine.

If this is a misunderstanding on my side, please help me catching on...
